---

# copy kvm-guest.ks to /var/tmp/
#
- name: Template the kickstart file to /var/tmp/
  ansible.builtin.template:
    src: kvm-guest.ks.j2
    dest: /var/tmp/kvm-guest.ks
    owner: root
    group: root
    mode: '0600'

# define and launch the guest

# sparse?
# Not sparse!
# I've done something wrong here, or in the kickstart file.
# 
- name: create
  ansible.builtin.command:
    cmd: >
      virt-install 
      --name="kvm-guest" 
      --vcpus=2 
      --ram=4096 
      --disk path=/var/lib/libvirt/images/kvm-guest.qcow2,bus=virtio,size=50,sparse=yes 
      --os-variant rhel8.2 
      --network network=default,mac=52:54:00:00:00:21   
      --boot uefi,hd,menu=on 
      --location /var/lib/libvirt/images/rhel-8.2-x86_64-dvd.iso 
      --initrd-inject /var/tmp/kvm-guest.ks 
      --extra-args "inst.ks=file:/kvm-guest.ks console=tty0 console=ttyS0,115200" 
      --noautoconsole
  register: r_virt_install

- name: display domain info
  ansible.builtin.debug:
    var: r_virt_install

- name: get domain info
  community.libvirt.virt:
    name: kvm-guest
    command: info
  register: r_domain_info

- name: display domain info
  debug:
    var: r_domain_info['kvm-guest']

